### PR TITLE
Feature/third widget Layouts fix

### LINKED ISSUE #18: Add third widget variation
https://helpukrainewinwidget.org/install-manually

image

image

image

### PR DESCRIPTION
**Pull request by F1fi**

### CODE REVIEW

File: lib/src/components/mini_chevron_left.dart [hunk 1]
```diff
@@ -0,0 +1,85 @@
+import 'package:flutter/material.dart';
+
+/// chevron Icon
+class MiniChevronLeft extends StatelessWidget {
```
Comment (solid-yuriiprykhodko) [inline lib/src/components/mini_chevron_left.dart]: Can't we reuse `ChevronDown`?

Comment (solid-yuriiprykhodko) [reply lib/src/components/mini_chevron_left.dart]: We could either work around this by just making `width` and `height` smaller, or we could add a `scale` argument to `Chevron` and reuse it.
Otherwise it's duplicate functionality.
image

Comment (F1fi) [reply lib/src/components/mini_chevron_left.dart]: i moved arrow to center of circle

**Review by solid-yuriiprykhodko — CHANGES_REQUESTED** [review]
Let's remove duplication in Chevron painting logic, and fix all lints.

**Comment by solid-yuriiprykhodko** [comment]
image
Font weight still not quite there.

**Comment by solid-yuriiprykhodko** [comment]
Not quite there:
image
image
1. Font weight must be bigger.
2. Button background color
3. Button text font weight and placement
4. Chevron size

**Comment by solid-yuriiprykhodko** [comment]
image

1. Font weight
2. Chevron for the "Back" button

**Comment by solid-yuriiprykhodko** [comment]
image

image

Font weight not quite right, character spacing could be closer to original.
Please try to make the widget look as close to the original as possible.

**Comment by F1fi** [comment]
image

**Comment by F1fi** [comment]
image

**Comment by F1fi** [comment]
image
left - widget from site
right - our widget

**Comment by solid-yuriiprykhodko** [comment]
@F1fi Try updating from `master` and checking again.
Make sure to build with `--web-renderer canvaskit`.

I've made some updates to the fonts: #27.

**Comment by solid-yuriiprykhodko** [comment]
Font weight needs to be a little higher:
image

Same for the options view:
image

File: lib/src/widgets/help_collection/square_help_widget.dart [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+        ),
+        onClose: _controller.goBack,
+        rightPosition: _rightClosePosition,
+        topPosition: _topClosePosition,
+        child: Column(
+          mainAxisSize: MainAxisSize.min,
+          children: [
+            Text(
+              title,
+              style: TextThemes.mainFont.copyWith(
```
Comment (solid-yuriiprykhodko) [inline lib/src/widgets/help_collection/square_help_widget.dart:86]: The font now matches perfectly -- the problem was that you weren't specifying font family, and used the standard sans-serif.
image

**Comment by solid-yuriiprykhodko** [comment]
image

1. Close button placement slightly off.
2. Chevron placement slightly off.

**Review by solid-yuriiprykhodko — APPROVED** [review]
LGTM!

**Review by solid-yuriiprykhodko — CHANGES_REQUESTED** [review]
Need to review naming and changes affecting other widgets.

**Comment by solid-oleksandrhordiienko** [comment]
image
left - widget from site
right - our widget
------------------
image
one on top of the other

**Comment by solid-oleksandrhordiienko** [comment]
image
left - widget from site,
right - our widget
image
one on top of the other

**Review by solid-yuriiprykhodko — CHANGES_REQUESTED** [review]
Let's resolve the conflicts before moving forward.

Also, the second and third line text is a bit mis-aligned:
image

Please also use the inverted image feature of the pixel-perfect tool for screenshots.

**Comment by solid-oleksandrhordiienko** [comment]
image
one on top of other

**Comment by solid-oleksandrhordiienko** [comment]
image

**Comment by solid-oleksandrhordiienko** [comment]
one on top of other mainView
image
image

**Comment by solid-oleksandrhordiienko** [comment]
optionsView (one on top of other)
image
image

**Review by solid-yuriiprykhodko — CHANGES_REQUESTED** [review]
This is what I see when I'm using the top left corner as an anchor to align with the original:

image

1. Card size off by 1-2px
2. Text placement off by 1-2 px
3. Close button way off.

**Comment by solid-oleksandrhordiienko** [comment]
image

**Comment by solid-yuriiprykhodko** [comment]
1. 1st widget, second view on `master`:

image

Has some problems, but pretty close to original.

---


2. Same view on this branch: 

image

Way off.

You've probably made some changes to the base widgets that caused this.

Please fix this and ensure that all other widgets are unchanged by this PR.

**Comment by solid-oleksandrhordiienko** [comment]
1-st widget
image

**Comment by solid-oleksandrhordiienko** [comment]
image

**Comment by solid-oleksandrhordiienko** [comment]
image
image

**Comment by solid-oleksandrhordiienko** [comment]
first widget
image
image
Second widget
image
image
Third widget
image
image

File: lib/src/components/card_rounded/card_rounded.dart [hunk 3]
```diff
@@ -84,12 +84,16 @@ class CardRounded extends StatelessWidget {
...
       final _defaultCloseButtonIcon = Container(
         padding: const EdgeInsets.all(_padding),
-        child: const XMark(
-          size: Size.square(_iconSize),
-          color: Colors.white,
-          lineWidth: _lineWidth,
+        child: Transform.scale(
+          scale: _scale,
+          child: const XMark(
+            size: Size.square(_iconSize),
```
Comment (solid-yuriiprykhodko) [inline lib/src/components/card_rounded/card_rounded.dart]: Why not adjust the size instead of using `Transform.scale`?

File: lib/src/helpers/default_options.dart [hunk 4]
```diff
@@ -0,0 +1 @@
+
```
Comment (solid-yuriiprykhodko) [inline lib/src/helpers/default_options.dart]: Empty file

File: lib/src/widgets/help_collection/square_help_widget.dart [hunk 5]
```diff
@@ -0,0 +1,116 @@
+import 'package:flutter/material.dart';
+import 'package:help_ukraine_widget/help_ukraine_widget.dart';
+import 'package:help_ukraine_widget/src/helpers/option_helper.dart';
+
+/// Variation of a [HelpWidget] with almost equal height and width.
+class SquareHelpWidget extends StatelessWidget {
+  final _controller = TraverseController(
+    [HelpWidgetView.collapsed, HelpWidgetView.main, HelpWidgetView.options],
```
Comment (solid-yuriiprykhodko) [inline lib/src/widgets/help_collection/square_help_widget.dart]: Nitpick:
```suggestion
    [HelpWidgetView.collapsed, HelpWidgetView.main, HelpWidgetView.options,],
```

File: lib/src/widgets/help_collection/square_help_widget.dart [hunk 6]
```diff
@@ -0,0 +1,116 @@
...
+      axis: Axis.horizontal,
+      optionsView: CardRounded(
+        onClose: _controller.goBack,
+        closeButtonIcon: Transform.scale(
+          scale: _chevronScale,
+          child: Transform.translate(
+            offset: _chevronOffset,
+            child: const Center(
+              child: Chevron(
+                size: Size.square(_iconSize / 2),
```
Comment (solid-yuriiprykhodko) [inline lib/src/widgets/help_collection/square_help_widget.dart]: Same as above -- let's adjust the size instead of using `Transform.scale`.

**Review by solid-yuriiprykhodko — CHANGES_REQUESTED** [review]
Just some minor cleanup.

**Review by solid-yuriiprykhodko — APPROVED** [review]
Looks good!
